---
image: alpine:latest

stages:
  - analysis
  - review
  - cleanup

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

include:
  - local: /.gitlab/analysis/lint.yml
  - local: /.gitlab/analysis/audit.yml
  - local: /.gitlab/deploy/dokku.yml

